### ISSUE TITLE
email as sub display error

### ISSUE THREAD

**Issue by lucakuendig** [TremoloSecurity/OpenUnison#641]
If you use oidc auth and then use the email from the token as the sub the --user option and the set-credentials from the kubectl command that can be copied from the login portal looks like this: "emailx-64-xdomain.local@context". It seems to substitue @ with x-64-x. 
This is not a huge issue but as I would like to migrate from dex to OpenUnison it is a problem with our current RBAC. Sometimes we use to bind roles in kubernetes directly to a user and until now we used to use email as the unique identifier. This would mean we have to change all our current bindings plus it would be a bit ugly to read. Is it possible to change it in a way that the kubectl commands in the portal would display it correctly?

**Comment by mlbiam** [comment]
What is your upstream identity provider (oidc, saml2, ldap/ad, github)?

**Comment by lucakuendig** [comment]
I tried it with our on prem gitlab instance and another time with our keycloak instance. Both led to the same effect. 
If I decode the token the email gets displayed correctly within the payload

**Comment by mlbiam** [comment]
> If I decode the token the email gets displayed correctly within the payload

right, that's what matters as far as RBAC is concerned.  When you run the command to get your kubectl user, you'll see:

```
Cluster "kubernetes" set.
Context "kubernetes" created.
User "marcx-43-xmmosleyx-64-xtremolo.io@kubernetes" set.
Switched to context "kubernetes".
```

The `x-64-x` is because we store all our state in the API server as CRDs and `@` isn't a valid character for `obj.metadata.name`.  This only pertains to kubectl though and doesn't impact RBAC, only what's in your `id_token`.  So as an example in my cluster I'm using with Okta with email as the `sub`, my id_token is: 

```json
{
  "iss": "https://k8sou.apps.192-168-2-43.nip.io/auth/idp/k8sIdp",
  "aud": "kubernetes",
  "exp": 1655986184,
  "jti": "Zvb7XAzL-qVhO2z7w5MhTg",
  "iat": 1655986124,
  "nbf": 1655986004,
  "sub": "marc+mmosley@tremolo.io",
  "name": " Mosley",
  "groups": [
    "demo-k8s",
    "Everyone",
    "k8s-users",
    "gsa-demo-users",
    "k8s-admins"
  ],
  "preferred_username": "marcx-43-xmmosleyx-64-xtremolo.io",
  "email": "marc+mmosley@tremolo.io"
}
```

The `sub` is a correct email address.  That's what you'll use for RBAC.

> Sometimes we use to bind roles in kubernetes directly to a user and until now we used to use email as the unique identifier

If you're using `sub` as your identifier in your API server flags, you need to prepend the issuer in your RBAC bindings anyways.  If you use `email` as your identifier in your API server flags you don't need to do this and shouldn't have to change your RBAC bindings.
